apiVersion: v1
kind: Secret
metadata:
  name: pipeline-auth
data:
  AZP_URL: 
  AZP_POOL: 
  AZP_TOKEN: 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdevops-deployment  
  labels:
    app: azdevops-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: azdevops-agent
  template:
    metadata:
      labels:
        app: azdevops-agent
    spec:
      containers:
      - name: azdevops-agent
        image: opensaturdaycontainerregistry.azurecr.io/dockeragent:ubuntu-20.04
        env:
          - name: AZP_URL
            valueFrom:
              secretKeyRef:
                name: pipeline-auth
                key: AZP_URL
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: pipeline-auth
                key: AZP_TOKEN
          - name: AZP_POOL
            valueFrom:
              secretKeyRef:
                name: pipeline-auth
                key: AZP_POOL
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-volume
      volumes:
      - name: docker-volume
        hostPath:
          path: /var/run/docker.sock